// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbxfmmepzpypbykphckq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtieGZtbWVwenB5cGJ5a3BoY2txIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzczNjQ1MjAsImV4cCI6MjA1Mjk0MDUyMH0.YJfGoJIHjOzYxpX4v4kxI-pn6xp2K6i9JD-Ak4KIE7w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);